### ISSUE TITLE
Improve errors

### ISSUE THREAD

**Issue by abunsen** [flomio/passninja-js#4]
https://github.com/flomio/passninja-core/issues/105

It would be really great if before you send a request to create a pass, you checked to make sure that all of the necessary fields are present. Maybe there is an endpoint that tells you all of the fields necessary for creating a specific pass type?

**Comment by AndresMWeber** [comment]
This was actually implemented with /passtypes/keys/:passtype which returns the list of required keys as a string array. The POST /passes endpoint also responds with a specific error that tells the user if they missed a key but it only reports key by key as you keep adding the missing keys, not an entire list.

**Comment by grundyoso** [comment]
fixed in #5
